import 'src/app_attest_platform_interface.dart';

export 'src/app_attest_platform_interface.dart' show AppAttestPlatform;

/// Result returned by Apple's App Attest attestation flow.
class AppAttestAttestation {
  /// Creates an attestation result.
  const AppAttestAttestation({
    required this.keyId,
    required this.attestationObject,
  });

  /// App Attest key identifier generated by iOS.
  final String keyId;

  /// Base64-encoded App Attest attestation object.
  final String attestationObject;

  /// Creates a result from a platform channel map.
  factory AppAttestAttestation.fromMap(Map<dynamic, dynamic> map) {
    return AppAttestAttestation(
      keyId: map['keyId'] as String,
      attestationObject: map['attestationObject'] as String,
    );
  }
}

/// Result returned by Apple's App Attest assertion flow.
class AppAttestAssertion {
  /// Creates an assertion result.
  const AppAttestAssertion({
    required this.keyId,
    required this.assertionObject,
  });

  /// App Attest key identifier used for this assertion.
  final String keyId;

  /// Base64-encoded App Attest assertion object.
  final String assertionObject;

  /// Creates a result from a platform channel map.
  factory AppAttestAssertion.fromMap(Map<dynamic, dynamic> map) {
    return AppAttestAssertion(
      keyId: map['keyId'] as String,
      assertionObject: map['assertionObject'] as String,
    );
  }
}

/// Flutter API for iOS App Attest and Android Play Integrity.
class AppAttest {
  const AppAttest._();

  /// Returns whether the native integrity service is available.
  static Future<bool> isSupported() => AppAttestPlatform.instance.isSupported();

  /// Generates an App Attest key on iOS and returns its key identifier.
  ///
  /// Store this identifier in your app and on your server after successful
  /// attestation. This method is iOS-only.
  static Future<String> generateKey() =>
      AppAttestPlatform.instance.generateKey();

  /// Attests an existing App Attest [keyId] against a server [challenge].
  ///
  /// The challenge is SHA-256 hashed natively before calling Apple's
  /// `DCAppAttestService.attestKey`. This method is iOS-only.
  static Future<AppAttestAttestation> attestKey({
    required String keyId,
    required String challenge,
  }) async {
    _checkNotEmpty(keyId, 'keyId');
    _checkNotEmpty(challenge, 'challenge');

    final result = await AppAttestPlatform.instance.attestKey(
      keyId: keyId,
      challenge: challenge,
    );
    return AppAttestAttestation.fromMap(result);
  }

  /// Generates an App Attest assertion for an already-attested [keyId].
  ///
  /// The challenge is SHA-256 hashed natively before calling Apple's
  /// `DCAppAttestService.generateAssertion`. This method is iOS-only.
  static Future<AppAttestAssertion> generateAssertion({
    required String keyId,
    required String challenge,
  }) async {
    _checkNotEmpty(keyId, 'keyId');
    _checkNotEmpty(challenge, 'challenge');

    final result = await AppAttestPlatform.instance.generateAssertion(
      keyId: keyId,
      challenge: challenge,
    );
    return AppAttestAssertion.fromMap(result);
  }

  /// Requests a Play Integrity token on Android.
  ///
  /// [nonce] must be generated by your server or be derived from a server
  /// challenge. [cloudProjectNumber] is the numeric Google Cloud project number
  /// configured for Play Integrity.
  static Future<String> requestPlayIntegrityToken({
    required String nonce,
    required int cloudProjectNumber,
  }) {
    _checkNotEmpty(nonce, 'nonce');
    if (cloudProjectNumber <= 0) {
      throw ArgumentError.value(
        cloudProjectNumber,
        'cloudProjectNumber',
        'Must be greater than zero.',
      );
    }

    return AppAttestPlatform.instance.requestPlayIntegrityToken(
      nonce: nonce,
      cloudProjectNumber: cloudProjectNumber,
    );
  }

  static void _checkNotEmpty(String value, String name) {
    if (value.trim().isEmpty) {
      throw ArgumentError.value(value, name, 'Must not be empty.');
    }
  }
}
