import 'src/app_attest_platform_interface.dart';

export 'src/app_attest_platform_interface.dart' show AppAttestPlatform;

/// Result returned by Apple's App Attest attestation flow.
class AppAttestAttestation {
  /// Creates an attestation result.
  const AppAttestAttestation({
    required this.keyId,
    required this.attestationObject,
  });

  /// App Attest key identifier generated by iOS.
  final String keyId;

  /// Base64-encoded App Attest attestation object.
  final String attestationObject;

  /// Creates a result from a platform channel map.
  factory AppAttestAttestation.fromMap(Map<dynamic, dynamic> map) {
    return AppAttestAttestation(
      keyId: map['keyId'] as String,
      attestationObject: map['attestationObject'] as String,
    );
  }
}

/// Result returned by Apple's App Attest assertion flow.
class AppAttestAssertion {
  /// Creates an assertion result.
  const AppAttestAssertion({
    required this.keyId,
    required this.assertionObject,
  });

  /// App Attest key identifier used for this assertion.
  final String keyId;

  /// Base64-encoded App Attest assertion object.
  final String assertionObject;

  /// Creates a result from a platform channel map.
  factory AppAttestAssertion.fromMap(Map<dynamic, dynamic> map) {
    return AppAttestAssertion(
      keyId: map['keyId'] as String,
      assertionObject: map['assertionObject'] as String,
    );
  }
}

/// Flutter API for iOS App Attest and Android Play Integrity.
class AppAttest {
  const AppAttest._();

  /// Returns whether the native integrity service is available.
  static Future<bool> isSupported() => AppAttestPlatform.instance.isSupported();

  /// Generates an App Attest key on iOS and returns its key identifier.
  ///
  /// Store this identifier in your app and on your server after successful
  /// attestation. This method is iOS-only.
  static Future<String> generateKey() =>
      AppAttestPlatform.instance.generateKey();

  /// Attests an existing App Attest [keyId] against a server [challenge].
  ///
  /// The challenge is SHA-256 hashed natively before calling Apple's
  /// `DCAppAttestService.attestKey`. This method is iOS-only.
  static Future<AppAttestAttestation> attestKey({
    required String keyId,
    required String challenge,
  }) async {
    _checkNotEmpty(keyId, 'keyId');
    _checkNotEmpty(challenge, 'challenge');

    final result = await AppAttestPlatform.instance.attestKey(
      keyId: keyId,
      challenge: challenge,
    );
    return AppAttestAttestation.fromMap(result);
  }

  /// Generates an App Attest assertion for an already-attested [keyId].
  ///
  /// The challenge is SHA-256 hashed natively before calling Apple's
  /// `DCAppAttestService.generateAssertion`. This method is iOS-only.
  static Future<AppAttestAssertion> generateAssertion({
    required String keyId,
    required String challenge,
  }) async {
    _checkNotEmpty(keyId, 'keyId');
    _checkNotEmpty(challenge, 'challenge');

    final result = await AppAttestPlatform.instance.generateAssertion(
      keyId: keyId,
      challenge: challenge,
    );
    return AppAttestAssertion.fromMap(result);
  }

  /// Prepares the Android Standard Play Integrity token provider.
  ///
  /// Call this well before the integrity token is needed, for example at app
  /// launch or shortly before a protected backend request.
  static Future<void> preparePlayIntegrityTokenProvider({
    required int cloudProjectNumber,
  }) {
    if (cloudProjectNumber <= 0) {
      throw ArgumentError.value(
        cloudProjectNumber,
        'cloudProjectNumber',
        'Must be greater than zero.',
      );
    }

    return AppAttestPlatform.instance.preparePlayIntegrityTokenProvider(
      cloudProjectNumber: cloudProjectNumber,
    );
  }

  /// Clears the cached Android Standard Play Integrity token provider.
  ///
  /// You typically do not need to call this manually, but it can be useful when
  /// your app signs out, changes backend environments, or wants to force a new
  /// provider warm-up.
  static Future<void> clearPreparedPlayIntegrityTokenProvider() {
    return AppAttestPlatform.instance.clearPreparedPlayIntegrityTokenProvider();
  }

  /// Requests an Android Standard Play Integrity token using a request hash.
  ///
  /// Before calling this method, warm up the provider with
  /// [preparePlayIntegrityTokenProvider].
  ///
  /// [requestHash] should be a stable hash of the protected request, such as a
  /// SHA-256 digest computed from the request payload or important parameters.
  static Future<String> requestStandardPlayIntegrityToken({
    required String requestHash,
  }) {
    _checkNotEmpty(requestHash, 'requestHash');

    return AppAttestPlatform.instance.requestStandardPlayIntegrityToken(
      requestHash: requestHash,
    );
  }

  /// Requests an Android Classic Play Integrity token using a nonce.
  ///
  /// Prefer [requestStandardPlayIntegrityToken] for new integrations. Use the
  /// Classic API only when your backend or product requirements still depend on
  /// the original nonce-based Play Integrity request flow.
  static Future<String> requestClassicPlayIntegrityToken({
    required String nonce,
    required int cloudProjectNumber,
  }) {
    _checkNotEmpty(nonce, 'nonce');
    if (cloudProjectNumber <= 0) {
      throw ArgumentError.value(
        cloudProjectNumber,
        'cloudProjectNumber',
        'Must be greater than zero.',
      );
    }

    return AppAttestPlatform.instance.requestClassicPlayIntegrityToken(
      nonce: nonce,
      cloudProjectNumber: cloudProjectNumber,
    );
  }

  /// Backwards-compatible alias for [requestClassicPlayIntegrityToken].
  @Deprecated(
    'Use requestClassicPlayIntegrityToken() for Classic API requests.',
  )
  static Future<String> requestPlayIntegrityToken({
    required String nonce,
    required int cloudProjectNumber,
  }) {
    return requestClassicPlayIntegrityToken(
      nonce: nonce,
      cloudProjectNumber: cloudProjectNumber,
    );
  }

  static void _checkNotEmpty(String value, String name) {
    if (value.trim().isEmpty) {
      throw ArgumentError.value(value, name, 'Must not be empty.');
    }
  }
}
